import jsPDF from "jspdf";
import QRCode from "qrcode";

export type CertificateData = {
  donorName: string;
  ngoName: string;
  amountPaise: number;
  mealsFunded: number;
  transactionId: string;
  timestampIso: string;
  certificateId: string;
};

export async function generateCertificatePdf(data: CertificateData) {
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();

  // Background
  doc.setFillColor(240, 253, 244);
  doc.rect(0, 0, w, h, "F");
  doc.setFillColor(255, 247, 237);
  doc.circle(w - 120, 110, 110, "F");

  // Header gradient strip (fake)
  doc.setFillColor(34, 197, 94);
  doc.rect(0, 0, w, 20, "F");
  doc.setFillColor(249, 115, 22);
  doc.rect(0, 20, w, 10, "F");

  // Brand
  doc.setTextColor(24, 24, 27);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text("FoodRescue AI", 56, 80);
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(63, 63, 70);
  doc.text("Expiry-Aware Real-Time Food Redistribution Network", 56, 102);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(34);
  doc.setTextColor(24, 24, 27);
  doc.text("Impact Certificate", 56, 160);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(14);
  doc.setTextColor(63, 63, 70);
  doc.text("Thank you for supporting humanity.", 56, 186);

  // Main card
  const cardX = 56;
  const cardY = 220;
  const cardW = w - 112;
  const cardH = h - 280;
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(cardX, cardY, cardW, cardH, 18, 18, "F");
  doc.setDrawColor(228, 228, 231);
  doc.roundedRect(cardX, cardY, cardW, cardH, 18, 18, "S");

  const leftX = cardX + 28;
  let y = cardY + 46;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(24, 24, 27);
  doc.text("Donor", leftX, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(18);
  doc.text(data.donorName, leftX + 80, y);

  y += 34;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("NGO", leftX, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(18);
  doc.text(data.ngoName, leftX + 80, y);

  y += 34;
  doc.setFont("helvetica", "bold");
  doc.text("Meals", leftX, y);
  doc.setFont("helvetica", "normal");
  doc.text(String(data.mealsFunded), leftX + 80, y);

  y += 34;
  doc.setFont("helvetica", "bold");
  doc.text("Amount", leftX, y);
  doc.setFont("helvetica", "normal");
  doc.text(formatInr(data.amountPaise), leftX + 80, y);

  y += 34;
  doc.setFont("helvetica", "bold");
  doc.text("Txn ID", leftX, y);
  doc.setFont("helvetica", "normal");
  doc.text(data.transactionId, leftX + 80, y);

  y += 34;
  doc.setFont("helvetica", "bold");
  doc.text("Time", leftX, y);
  doc.setFont("helvetica", "normal");
  doc.text(new Date(data.timestampIso).toLocaleString("en-IN"), leftX + 80, y);

  // QR
  const qrPayload = JSON.stringify({
    certificateId: data.certificateId,
    txn: data.transactionId,
    ngo: data.ngoName,
    meals: data.mealsFunded,
    at: data.timestampIso
  });
  const qrDataUrl = await QRCode.toDataURL(qrPayload, { margin: 1, scale: 6 });
  const qrSize = 140;
  const qrX = cardX + cardW - qrSize - 34;
  const qrY = cardY + 38;
  doc.addImage(qrDataUrl, "PNG", qrX, qrY, qrSize, qrSize);
  doc.setFontSize(11);
  doc.setTextColor(82, 82, 91);
  doc.text("Scan to verify (demo)", qrX, qrY + qrSize + 16);

  // Footer note
  doc.setFontSize(10);
  doc.setTextColor(113, 113, 122);
  doc.text(
    `Certificate ID: ${data.certificateId} • Generated by FoodRescue AI`,
    cardX + 28,
    cardY + cardH - 22
  );

  const blob = doc.output("blob");
  return blob;
}

function formatInr(amountPaise: number) {
  const inr = amountPaise / 100;
  return inr.toLocaleString("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0
  });
}

