server:
  port: ${PORT:8085}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/foodrescue_donations?options=-c%20TimeZone%3DUTC}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      data-source-properties:
        options: "-c TimeZone=UTC"
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3005}
  razorpay:
    key-id: ${RAZORPAY_KEY_ID:rzp_test_Sk6ZW4Ix9dWAkI}
    key-secret: ${RAZORPAY_KEY_SECRET:99HnMdFJYuT1rVuIbuH1yopQ}
    webhook-secret: ${RAZORPAY_WEBHOOK_SECRET:} # optional for MVP

