server:
  port: ${PORT:8085}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/foodrescue_donations}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3005}
  razorpay:
    key-id: ${RAZORPAY_KEY_ID:}
    key-secret: ${RAZORPAY_KEY_SECRET:}
    webhook-secret: ${RAZORPAY_WEBHOOK_SECRET:} # optional for MVP

